services:
  _defaults:
    autowire: true
    autoconfigure: true

  inisire\RPC\:
    resource: '../../../src/*'

  inisire\DataObject\:
    resource: '../../../../data-object/src/'

  inisire\RPC\Routing\RouteLoader:
    tags: ['routing.loader']

  inisire\RPC\DataObject\ObjectReferenceSerializerFactory:
    arguments: [
      !tagged_locator { tag: 'data_object.object_reference_loader' }
    ]

  inisire\DataObject\Serializer\ObjectReferenceSerializer:
    factory: ['@inisire\RPC\DataObject\ObjectReferenceSerializerFactory', 'create']

  inisire\DataObject\DataSerializerProvider:
    lazy: true
    class: inisire\RPC\DataObject\DataSerializerProvider
    arguments: [
      !tagged_locator { tag: 'rpc.data_serializer' },
    ]

  inisire\RPC\Entrypoint\EntrypointRegistry:
    arguments:
      $container: !tagged_locator { tag: 'rpc.command_handler' }